all: ear mouth launcher ui brain

ear: ear.c
	gcc -o ear ear.c

mouth: mouth.c
	gcc -o mouth mouth.c

launcher: launcher.c
	gcc -o launcher launcher.c

ui: ui.c
	gcc -o ui ui.c

brain: brain.c
	gcc -o brain brain.c

clean:
	rm launcher ear mouth ui 3000 4000 5000 6000 brain
